# appveyor.yml
---
environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pyqt coverage
  - conda activate test-environment
  - pip install tox

test_script:
- tox

after_test: coverage combine && codecov