language: python
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - python -m pip install --upgrade pip

addons:
  apt:
    packages:
      - python3-pyqt5

matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python3 -m virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate

install:
  - pip install coverage
  - pip install tox tox-travis
  - pip install setuptools
  - pip install wheel


script:
  - python

after_success: coverage combine && codecov