language: python
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"


install:
  - pip install coverage
  - pip install tox tox-travis
  - python setup.py bdist_wheel


script:
  - tox

after_success: coverage combine && codecov