name: pymodaq
dependencies:
    - python=3.7
    - pyqt
    - numpy==1.19.3
    - scipy>=1.3
    - pytables
    - pip
    - pip:
        - pymodaq_plugins
        - pymodaq_pid_models
        - pymodaq_plugin_manager
