name: pymodaq
dependencies:
    - python=3.7
    - pyqt
    - pip
    - pip:
        - numpy==1.19.3
        - scipy>=1.3
        - pytables
        - pymodaq_plugins
        - pymodaq_pid_models
        - pymodaq_plugin_manager
        - pyqtgraph==0.10
        - easydict
        - pymodaq_plugins>=2.0.1
        - pymodaq_pid_models>=0.0.2
	    - simple_pid
        - python-dateutil
        - packaging
        - SQLAlchemy-Utils==0.36.6 #this is so that the check for database existence doesn't crash anymore, see pull request 463
