name: Python3.7

on:
    workflow_call:
      inputs:
        python:
          required: true
          type: string
        qt5:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      