name: Python3.7

on:
    workflow_call:
      inputs:
        python:
          required: true
          type: string
        qt5:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python }}
      